<?php

namespace App\Core\Builder;

interface SQLQueryBuilderInterface
{
    public function select(string $table, array $fields): QueryBuilder;

    public function where(string $field, string $value, string $operator = '='): QueryBuilder;

    public function limit(int $start, int $offset): QueryBuilder;

    public function insert(string $table, array $data): bool;

    public function update(string $table, array $data, string $where): bool;
}