@base_url = http://localhost:8080/api/v1

###Homepage
GET http://localhost:8080

###Login
POST {{base_url}}/login
Content-Type: application/json

{
  "email": "m3rl1n1k@gmail.com",
  "password": "1111"
}

###Registration
POST {{base_url}}/registration
Content-Type: application/json

{
  "email": "m3rl1n1k@gmail.com",
  "password": "1111",
  "re-password": "1111",
  "name": "Serhii"
}

###Get All products
GET {{base_url}}/products/index?type=shoes

### New product
POST {{base_url}}/product/new/shoes
Content-Type: application/json

{
  "name": "Training Shoes",
  "size": {
    "38": true,
    "39": true,
    "40": false
  },
  "color": "Green",
  "article": 9474480,
  "brand": "Under Armour",
  "model": "Project Rock",
  "price": 149,
  "genre": "Woman",
  "description": "Durable training shoes for gym workouts",
  "image": "path/to/image5.jpg"
}

### Get single product
GET {{base_url}}/product/show/9474475


