@base_url = http://localhost:8080/api/v1

###Get All products
GET {{base_url}}/index

### New product
POST {{base_url}}/product/new
Content-Type: application/json

{
  "9474476": {
    "name": "snickers",
    "size": {
      "40": true,
      "41": true,
      "42": false
    },
    "color": "purple",
    "art": 9474476,
    "brand": "nike",
    "model": "Air max",
    "price": 199,
    "genre": "man",
    "description": "Some description about product",
    "image": "path to image"
  }
}

### Get single product
GET {{base_url}}/product/show/9474475


